import { Filter } from 'lucide-react';
import { Badge, Panel } from '../../../../components/ui';
import { ContactFilterSet, ContactTab } from '../../../../types';

type ContactSelectionFiltersProps = {
  tab: ContactTab;
  filters: ContactFilterSet;
};

const getFilterHeading = (tab: ContactTab) =>
  tab === 'recommended' ? 'AI Applied Filters' : 'Active Filters';

const getFilterDescription = (tab: ContactTab, hasFilters: boolean) => {
  if (tab === 'recommended') {
    return 'These filters were generated by our AI to zero in on the best contacts for this campaign.';
  }
  if (hasFilters) {
    return 'Filters currently narrowing this list of media contacts.';
  }
  return 'All Contacts opens without filters so you can browse the full list.';
};

export const ContactSelectionFilters = ({ tab, filters }: ContactSelectionFiltersProps) => {
  const filterSections: Array<{ key: keyof ContactFilterSet; label: string; values: string[] }> = [
    { key: 'countries', label: 'Countries', values: filters.countries },
    { key: 'beats', label: 'Beats', values: filters.beats },
    { key: 'languages', label: 'Languages', values: filters.languages },
    { key: 'mediaTypes', label: 'Media Types', values: filters.mediaTypes },
  ];

  const hasFilters = filterSections.some(section => section.values.length > 0);

  // Hide the entire panel when no filters are selected
  if (!hasFilters) {
    return null;
  }

  const badgeVariant = tab === 'recommended' ? 'default' : 'outline';

  return (
    <div className="mt-4 border-t border-border pt-4">
      <Panel padding="md" className="bg-muted/20 shadow-inner">
        <div className="flex flex-col gap-4">
          <div className="flex items-start gap-3">
            <span className="rounded-md bg-surface p-2 text-foreground shadow-sm">
              <Filter className="h-4 w-4" />
            </span>
            <div className="flex-1">
              <span className="text-sm font-semibold text-foreground">
                {getFilterHeading(tab)}
              </span>
            </div>
          </div>

          <div className="space-y-3">
            {filterSections.map(section => {
              if (section.values.length === 0) {
                return null;
              }

              return (
                <div
                  key={section.key}
                  className="rounded-lg border border-border bg-surface shadow-sm"
                >
                  <div className="border-b border-border px-3 py-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                    {section.label}
                  </div>
                  <div className="flex flex-wrap gap-2 px-3 py-3">
                    {section.values.map(value => (
                      <Badge
                        key={`${section.key}-${value}`}
                        variant={badgeVariant}
                        className="px-3 py-1 text-xs font-semibold"
                      >
                        {value}
                      </Badge>
                    ))}
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </Panel>
    </div>
  );
};
