import { MediaContact } from '../../../types';

export const initialContactsData: MediaContact[] = [
  {
    id: 1,
    initials: 'TJ',
    name: 'Temitayo Jaiyeola',
    outlet: 'BusinessDay',
    email: 'temitayoj@gmail.com',
    type: 'Journalist',
    language: 'EN',
    country: 'Nigeria',
    beats: 'SaaS, Startups, Funding',
    matchScore: 92,
    recommended: false,
    pitched: false,
    userAdded: false,
  },
  {
    id: 2,
    initials: 'SW',
    name: 'Sam Wakoba',
    outlet: 'Tech Moran',
    email: 'wakobasam@gmail.com',
    type: 'Podcaster',
    language: 'EN',
    country: 'Nigeria',
    beats: 'AI, B2B Software',
    matchScore: 96,
    recommended: true,
    pitched: false,
    userAdded: false,
  },
  {
    id: 3,
    initials: 'FE',
    name: 'Frank Eleanya',
    outlet: 'TechCabal',
    email: 'frankelean1283@gmail.com',
    type: 'TV Journalist',
    language: 'EN',
    country: 'Nigeria',
    beats: 'Enterprise Tech, Cloud',
    matchScore: 94,
    recommended: true,
    pitched: false,
    userAdded: false,
  },
  {
    id: 4,
    initials: 'FC',
    name: 'Florence Chikezie',
    outlet: 'Entrepreneurs.ng',
    email: 'business@entrepreneurs.ng',
    type: 'Magazine Writer',
    language: 'EN',
    country: 'Kenya',
    beats: 'Entrepreneurship, Growth',
    matchScore: 90,
    recommended: true,
    pitched: false,
    userAdded: false,
  },
  {
    id: 5,
    initials: 'SA',
    name: 'Samson Akintaro',
    outlet: 'Naira Metrics',
    email: 'samsonakintaro@yahoo.com',
    type: 'Youtuber',
    language: 'EN',
    country: 'Nigeria',
    beats: 'Finance, Analytics',
    matchScore: 84,
    recommended: false,
    pitched: false,
    userAdded: false,
  },
  {
    id: 6,
    initials: 'ST',
    name: 'Steve T',
    outlet: 'Owogram',
    email: 'steve@owogram.com',
    type: 'Tiktoker',
    language: 'FR',
    country: 'Ghana',
    beats: 'Tech Stories, Innovation',
    matchScore: 80,
    recommended: false,
    pitched: false,
    userAdded: false,
  },
  {
    id: 7,
    initials: 'ZK',
    name: 'Zainab Kabir',
    outlet: 'TechByte',
    email: 'zainab@techbyte.com',
    type: 'Journalist',
    language: 'EN',
    country: 'Nigeria',
    beats: 'Hardware, Gadgets',
    matchScore: 88,
    recommended: false,
    pitched: false,
    userAdded: false,
  },
  {
    id: 8,
    initials: 'LM',
    name: 'Lebo Mashaba',
    outlet: 'Digital Africa',
    email: 'lebo@digitalafrica.co.za',
    type: 'Newspaper Writer',
    language: 'EN',
    country: 'South Africa',
    beats: 'Fintech, VC',
    matchScore: 86,
    recommended: false,
    pitched: false,
    userAdded: false,
  },
  {
    id: 9,
    initials: 'AO',
    name: 'Adaora Okafor',
    outlet: 'Tech Founders Digest',
    email: 'adaora@foundersdigest.com',
    type: 'Blogger',
    language: 'EN',
    country: 'Kenya',
    beats: 'Startups, Product Launches',
    matchScore: 83,
    recommended: false,
    pitched: false,
    userAdded: false,
  },
];
